{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "from __future__ import division\n",
    "from utils import *\n",
    "from functions import *\n",
    "from numba import autojit\n",
    "import time\n",
    "%matplotlib inline\n",
    "\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "today = datetime.date.today()\n",
    "todayStr = '%04d%02d%02d' % (today.year, today.month, today.day)\n",
    "# todayStr = '20151005'\n",
    "DIRECTORY = os.path.expanduser(\"~/Dropbox/0000 - PhD/figures/\"+todayStr+\"/\")\n",
    "if not os.path.exists(DIRECTORY):\n",
    "    os.makedirs(DIRECTORY)\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "%%javascript\n",
    "IPython.OutputArea.auto_scroll_threshold = 9999;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# load classes\n",
    "gr = GRAPH()\n",
    "\n",
    "matplotlib.rc('xtick', labelsize=10)\n",
    "matplotlib.rc('ytick', labelsize=10)\n",
    "matplotlib.rc('axes', labelsize = 10)\n",
    "matplotlib.rc('axes', titlesize = 10)\n",
    "matplotlib.rc('lines', linewidth=2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "WII = 100\n",
    "N = 500\n",
    "s = 30\n",
    "index = 35\n",
    "for WII in np.arange(100,2000,100):\n",
    "    for s in np.arange(0,100,10):\n",
    "        index +=1\n",
    "        data_name = \"data-%d_WII-%d_N-%d_s-%d\" %(index, WII, N, s)\n",
    "        path = os.path.expanduser(\"/Users/GP1514/Dropbox/ICL-2014/Code/C-Code/cortex/scripts/%s.sh\"%data_name)\n",
    "        content = \"\"\"#!/bin/bash\n",
    "        N=8\n",
    "        trap 'exit' INT\n",
    "        num=$(awk 'BEGIN{for(i=0;i<4;i+=0.5)print i}')\n",
    "        num2=$(awk 'BEGIN{for(i=0;i<100;i+=10)print i}')\n",
    "        for n in $num\n",
    "        do\n",
    "          # ===============================================\n",
    "          # Beginning of inner loop.\n",
    "          (\n",
    "          for j in $num2\n",
    "          do\n",
    "                ((i=i%%N)); ((i++==0)) && wait\n",
    "                ../cortex/cortex -G $n -S $j -N %d -r 0.8 -d1 10 -d2 3000 -d3 10 -before 10 -after 3010 -s %d -WII %d -output _data_%d-wii%d-n%d-r08-s%d -model gp-izh &\n",
    "          done\n",
    "          )\n",
    "          # End of inner loop.\n",
    "          # ===============================================\n",
    "        done\n",
    "        # End of outer loop.\n",
    "        exit 0\n",
    "        \"\"\" % (N, s, WII,index, WII, N,s)\n",
    "\n",
    "        with open(path,\"w\") as f:\n",
    "            os.chmod(path, 0o770)\n",
    "            f.write(content)\n",
    "\n",
    "        print(\"start\")\n",
    "        subprocess.call([path])\n",
    "        time.sleep(10)\n",
    "        print(\"end\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "WII = 100\n",
    "N = 500\n",
    "s = 30\n",
    "index = 35\n",
    "for WII in np.arange(100,2000,100):\n",
    "    for s in np.arange(0,100,10):\n",
    "        index +=1\n",
    "        data_name = \"_data_%d-wii%d-n%d-r08-s%d.csv\" %(index,WII,N,s)\n",
    "        path = os.path.expanduser(\"/Users/GP1514/Dropbox/ICL-2014/Code/C-Code/cortex/data/%s\"%data_name)\n",
    "        column_names =['gammaC','nuEI','corI', 'spike','non-burst','burst', 'freq','power']\n",
    "        df = pd.read_csv(path, names= column_names ,  dtype ='float32' , sep=\";\")\n",
    "        df = df.fillna(10)\n",
    "        # print(df.head())\n",
    "        df= df[(df['nuEI']<200)]\n",
    "        # print(len(pd.unique(df.nuEI.ravel())))\n",
    "\n",
    "        fig=plt.figure(figsize=(6,4))\n",
    "        ###################################\n",
    "        # bursting\n",
    "        ###################################\n",
    "        dataframe = df[(df['freq']<1000)]\n",
    "        dataframe = df\n",
    "\n",
    "        title = r'Phase state diagram $bursting$ %s'%data_name\n",
    "        filename = \"global_gap_junctions_bursting.pdf\" \n",
    "        dataframe['logburst'] =(dataframe['burst']).apply(np.log10)\n",
    "        column = 'logburst'\n",
    "        ax = fig.add_subplot(111)\n",
    "        gr.plotDiagram(fig, ax, dataframe, title, column, filename, save=None, gridsize=60, extent = [0,4,0,100])\n",
    "        plt.savefig(DIRECTORY + 'bursting_phase_plan_%s.pdf'%data_name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "\n",
    "data_name = \"_data_%d-wii%d-n%d-r08-s%d.csv\" %(index,WII,N,s)\n",
    "path = os.path.expanduser(\"/Users/GP1514/Dropbox/ICL-2014/Code/C-Code/cortex/data/%s\"%data_name)\n",
    "column_names =['gammaC','nuEI','corI', 'spike','non-burst','burst', 'freq','power']\n",
    "df = pd.read_csv(path, names= column_names ,  dtype ='float32' , sep=\";\")\n",
    "df = df.fillna(10)\n",
    "# print(df.head())\n",
    "df= df[(df['nuEI']<200)]\n",
    "# print(len(pd.unique(df.nuEI.ravel())))\n",
    "\n",
    "fig=plt.figure(figsize=(6,4))\n",
    "###################################\n",
    "# bursting\n",
    "###################################\n",
    "df_sliced = df[(df['freq']<1000) & (df['burst']>0.00001)]\n",
    "df_sliced['ratio'] =((df_sliced['burst'])/df_sliced['non-burst']).apply(np.log10)\n",
    "dataframe = df_sliced\n",
    "title = r'Phase state diagram ratio $bursting/spiking$'\n",
    "filename = \"global_gap_junctions_c%d_ratio.pdf\"\n",
    "column = 'ratio'\n",
    "ax = fig.add_subplot(111)\n",
    "gr.plotDiagram(fig, ax, dataframe, title, column, filename, save=None, gridsize=60, extent = [0,4,0,100])\n",
    "plt.savefig(DIRECTORY + 'ratio_%s.pdf'%data_name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "def plotAll(data_name):\n",
    "    path = os.path.expanduser(\"/Users/GP1514/Dropbox/ICL-2014/Code/C-Code/cortex/data/%s\"%data_name)\n",
    "    column_names =['gammaC','nuEI','corI', 'spike','non-burst','burst', 'freq','power']\n",
    "    df = pd.read_csv(path, names= column_names ,  dtype ='float32' , sep=\";\")\n",
    "    df = df.fillna(10)\n",
    "    # print(df.head())\n",
    "    df= df[(df['nuEI']<200)]\n",
    "    c=0\n",
    "    figsize = (10,5)\n",
    "    fig = plt.figure(figsize=figsize)\n",
    "    gridsize=60\n",
    "    ###################################\n",
    "    # spiking\n",
    "    ###################################\n",
    "    dataframe = df[(df['freq']<1000)]\n",
    "    title = r'Phase state diagram $spiking$'\n",
    "    filename = \"global_gap_junctions_c%d_spiking.pdf\" %c\n",
    "    column = 'non-burst'\n",
    "    ax = fig.add_subplot(231)\n",
    "    gr.plotDiagram(fig, ax, dataframe, title, column, filename, save=None, gridsize=gridsize, extent = [0,4,0,100] )\n",
    "\n",
    "    ###################################\n",
    "    # bursting\n",
    "    ###################################\n",
    "    dataframe = df[(df['freq']<1000)]\n",
    "    title = r'Phase state diagram $bursting$'\n",
    "    filename = \"global_gap_junctions_c%d_bursting.pdf\" %c\n",
    "    dataframe['logburst'] =(dataframe['burst']).apply(np.log10)\n",
    "    column = 'logburst'\n",
    "    ax = fig.add_subplot(232)\n",
    "    gr.plotDiagram(fig, ax, dataframe, title, column, filename, save=None, gridsize=gridsize, extent = [0,4,0,100] )\n",
    "\n",
    "    ###################################\n",
    "    # ratio\n",
    "    ###################################\n",
    "    df_sliced = df[(df['freq']<1000) & (df['burst']>0.00001)]\n",
    "    df_sliced['ratio'] =((df_sliced['burst'])/df_sliced['non-burst']).apply(np.log10)\n",
    "    dataframe = df_sliced\n",
    "    title = r'Phase state diagram ratio $bursting/spiking$'\n",
    "    filename = \"global_gap_junctions_c%d_ratio.pdf\"\n",
    "    column = 'ratio'\n",
    "    ax = fig.add_subplot(233)\n",
    "    gr.plotDiagram(fig, ax, dataframe, title, column, filename, save=None, gridsize=gridsize, extent = [0,4,0,100] )\n",
    "\n",
    "    # ###################################\n",
    "    # # corI\n",
    "    # ###################################\n",
    "    # dataframe = df[(df['freq']<1000)]\n",
    "    # title = r'Phase state diagram $corI$')\n",
    "    # filename = \"global_gap_junctions_c%d_corI.pdf\" %c\n",
    "    # column = 'corI'\n",
    "    # fig = plt.figure(figsize=figsize)\n",
    "    # ax = fig.add_subplot(111)\n",
    "    # plotDiagram(fig, ax, dataframe, title, column, filename)\n",
    "\n",
    "    ###################################\n",
    "    # power\n",
    "    ###################################\n",
    "    dataframe = df[(df['freq']<1000)]\n",
    "    ttl = r'Phase state diagram $P_dB(f)$'\n",
    "    filename = \"global_gap_junctions_c%d_power.pdf\" %c\n",
    "    dataframe['logpower'] =(dataframe['power']).apply(np.log10)\n",
    "    column = 'logpower'\n",
    "    ax = fig.add_subplot(234)\n",
    "    gr.plotDiagram(fig, ax, dataframe, ttl, column, filename, save=None, front=False, gridsize=gridsize, extent = [0,4,0,100] )\n",
    "\n",
    "    ###################################\n",
    "    # power freq\n",
    "    ###################################\n",
    "    dataframe = df[(df['freq']<1000)]\n",
    "    dataframe['logpower'] =(dataframe['power']).apply(np.log10)\n",
    "    # dataframe = dataframe[(dataframe['logpower']>-1)]\n",
    "    title = r'Phase state diagram $freq  Pdb>0.1$'\n",
    "    filename = \"global_gap_junctions_c%d_power_freq.pdf\" %c\n",
    "    column = 'freq'\n",
    "    ax = fig.add_subplot(235)\n",
    "    gr.plotDiagram(fig, ax, dataframe, title, column, filename, save=None,  front=False, gridsize=gridsize, extent = [0,4,0,100] )\n",
    "\n",
    "\n",
    "    ax = fig.add_subplot(236)\n",
    "    ax.set_title(data_name)\n",
    "    ax.set_xticks([])\n",
    "    ax.set_yticks([])\n",
    "    ax.set_axis_bgcolor((1, 1,1))\n",
    "    ax.text(0.1,0.1, r'$W_{II} = %d$'%WII, fontsize=15, color='green')\n",
    "    ax.text(0.1,0.5, r'$\\sigma = %d$'%s, fontsize=15, color='red')\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(DIRECTORY + 'all_%s.png'%data_name)\n",
    "    plt.close(fig)\n",
    "#         plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(10, 8)\n",
      "(10, 8)\n",
      "(1, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "Error reshaping array\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "Error reshaping array\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "Error reshaping array\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "Error reshaping array\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(3, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "Error reshaping array\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "Error reshaping array\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 7)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "Error reshaping array\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)\n",
      "(10, 8)"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/ipykernel/__main__.py:37: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy\n",
      "ERROR: "
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 3066, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-5-9a355c273c13>\", line 9, in <module>\n",
      "    plotAll(data_name)\n",
      "  File \"<ipython-input-3-c5f99365490a>\", line 88, in plotAll\n",
      "    plt.savefig(DIRECTORY + 'all_%s.png'%data_name)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/pyplot.py\", line 689, in savefig\n",
      "    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/backend_bases.py\", line 2026, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py\", line 474, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/artist.py\", line 61, in draw_wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/figure.py\", line 1133, in draw\n",
      "    func(*args)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/artist.py\", line 61, in draw_wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/axes/_base.py\", line 2304, in draw\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/artist.py\", line 61, in draw_wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/text.py\", line 749, in draw\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/text.py\", line 361, in _get_layout\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py\", line 234, in get_text_width_height_descent\n",
      "    self.mathtext_parser.parse(s, self.dpi, prop)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 3118, in parse\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 2368, in parse\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1115, in parseString\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2378, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2732, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2361, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1015, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 779, in wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 2439, in math_string\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1115, in parseString\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2774, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2361, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2816, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1015, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 779, in wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 2494, in symbol\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 1329, in __init__\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 1336, in _update_metrics\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 466, in get_metrics\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 601, in _get_info\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 697, in _get_glyph\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 582, in _get_font\n",
      "OSError: [Errno 24] Too many open files: '/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmr10.ttf'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1877, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'OSError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 970, in get_records\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 233, in wrapped\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 267, in _fixed_getinnerframes\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/inspect.py\", line 1452, in getinnerframes\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/inspect.py\", line 1409, in getframeinfo\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/inspect.py\", line 671, in getsourcefile\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/inspect.py\", line 700, in getmodule\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/inspect.py\", line 684, in getabsfile\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/posixpath.py\", line 361, in abspath\n",
      "OSError: [Errno 24] Too many open files\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 3066, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-5-9a355c273c13>\", line 9, in <module>\n",
      "    plotAll(data_name)\n",
      "  File \"<ipython-input-3-c5f99365490a>\", line 88, in plotAll\n",
      "    plt.savefig(DIRECTORY + 'all_%s.png'%data_name)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/pyplot.py\", line 689, in savefig\n",
      "    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/backend_bases.py\", line 2026, in draw_idle\n",
      "    self.draw(*args, **kwargs)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py\", line 474, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/artist.py\", line 61, in draw_wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/figure.py\", line 1133, in draw\n",
      "    func(*args)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/artist.py\", line 61, in draw_wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/axes/_base.py\", line 2304, in draw\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/artist.py\", line 61, in draw_wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/text.py\", line 749, in draw\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/text.py\", line 361, in _get_layout\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py\", line 234, in get_text_width_height_descent\n",
      "    self.mathtext_parser.parse(s, self.dpi, prop)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 3118, in parse\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 2368, in parse\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1115, in parseString\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2378, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2732, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2361, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1015, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 779, in wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 2439, in math_string\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1115, in parseString\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2774, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2361, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2816, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1015, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 779, in wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 2494, in symbol\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 1329, in __init__\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 1336, in _update_metrics\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 466, in get_metrics\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 601, in _get_info\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 697, in _get_glyph\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 582, in _get_font\n",
      "OSError: [Errno 24] Too many open files: '/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmr10.ttf'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1877, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'OSError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 3006, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 3083, in run_code\n",
      "    self.showtraceback()\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1880, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1242, in structured_traceback\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1150, in structured_traceback\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1002, in structured_traceback\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 951, in format_exception_as_a_whole\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 724, in format_records\n",
      "TypeError: 'NoneType' object is not iterable\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1877, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 970, in get_records\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 233, in wrapped\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 267, in _fixed_getinnerframes\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/inspect.py\", line 1452, in getinnerframes\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/inspect.py\", line 1409, in getframeinfo\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/inspect.py\", line 671, in getsourcefile\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/inspect.py\", line 700, in getmodule\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/inspect.py\", line 684, in getabsfile\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/posixpath.py\", line 361, in abspath\n",
      "OSError: [Errno 24] Too many open files\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "\n",
      "Unfortunately, your original traceback can not be constructed.\n",
      "\n",
      "ERROR: Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "\n",
      "Unfortunately, your original traceback can not be constructed.\n",
      "\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "'NoneType' object is not iterable",
     "output_type": "error",
     "traceback": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 3066, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-5-9a355c273c13>\", line 9, in <module>\n    plotAll(data_name)\n",
      "  File \"<ipython-input-3-c5f99365490a>\", line 88, in plotAll\n    plt.savefig(DIRECTORY + 'all_%s.png'%data_name)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/pyplot.py\", line 689, in savefig\n    fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/backend_bases.py\", line 2026, in draw_idle\n    self.draw(*args, **kwargs)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py\", line 474, in draw\n    self.figure.draw(self.renderer)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/artist.py\", line 61, in draw_wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/figure.py\", line 1133, in draw\n    func(*args)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/artist.py\", line 61, in draw_wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/axes/_base.py\", line 2304, in draw\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/artist.py\", line 61, in draw_wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/text.py\", line 749, in draw\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/text.py\", line 361, in _get_layout\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py\", line 234, in get_text_width_height_descent\n    self.mathtext_parser.parse(s, self.dpi, prop)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 3118, in parse\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 2368, in parse\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1115, in parseString\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2378, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2732, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2361, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1015, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 779, in wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 2439, in math_string\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1115, in parseString\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2774, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2361, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2816, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2624, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 989, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 2483, in parseImpl\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1046, in _parseCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 1015, in _parseNoCache\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/pyparsing.py\", line 779, in wrapper\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 2494, in symbol\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 1329, in __init__\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 1336, in _update_metrics\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 466, in get_metrics\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 601, in _get_info\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 697, in _get_glyph\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mathtext.py\", line 582, in _get_font\n",
      "OSError: [Errno 24] Too many open files: '/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmr10.ttf'\n",
      "\nDuring handling of the above exception, another exception occurred:\n\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1877, in showtraceback\n    stb = value._render_traceback_()\n",
      "AttributeError: 'OSError' object has no attribute '_render_traceback_'\n",
      "\nDuring handling of the above exception, another exception occurred:\n\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 3006, in run_ast_nodes\n    if self.run_code(code, result):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 3083, in run_code\n    self.showtraceback()\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1880, in showtraceback\n    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1242, in structured_traceback\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1150, in structured_traceback\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1002, in structured_traceback\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 951, in format_exception_as_a_whole\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 724, in format_records\n",
      "TypeError: 'NoneType' object is not iterable\n",
      "\nDuring handling of the above exception, another exception occurred:\n\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1877, in showtraceback\n    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\nDuring handling of the above exception, another exception occurred:\n\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/ipykernel/ipkernel.py\", line 175, in do_execute\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2902, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 3031, in run_ast_nodes\n    self.showtraceback()\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 1880, in showtraceback\n    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1242, in structured_traceback\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1150, in structured_traceback\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 1020, in structured_traceback\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 951, in format_exception_as_a_whole\n",
      "  File \"/Users/GP1514/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/IPython/core/ultratb.py\", line 724, in format_records\n",
      "TypeError: 'NoneType' object is not iterable\n"
     ]
    }
   ],
   "source": [
    "WII = 100\n",
    "N = 500\n",
    "s = 30\n",
    "index = 35\n",
    "for WII in np.arange(100,2000,100):\n",
    "    for s in np.arange(0,100,10):\n",
    "        index +=1\n",
    "        data_name = \"_data_%d-wii%d-n%d-r08-s%d.csv\" %(index,WII,N,s)\n",
    "        plotAll(data_name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
